### ISSUE TITLE
Consider adding these resources

### ISSUE THREAD

**Issue by publicarray** [jonathandion/awesome-emails#21]
https://mailinabox.email/

https://iredmail.org/

https://github.com/cyrusimap/cyrus-imapd

https://arstechnica.com/information-technology/2014/02/how-to-run-your-own-e-mail-server-with-your-own-domain-part-1/

https://workaround.org/ispmail

**Comment by jonathandion** [comment]
@publicarray feel free to open a PR thanks.

**Comment by publicarray** [comment]
I just wanted to discuss first if the links are appropriate for the awesome list. i.e high quality and awesome.
